# Generated by Django 3.1.3 on 2020-12-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField(db_column='Food')),
                ('servings', models.IntegerField(blank=True, db_column='Servings', null=True)),
                ('ingredients', models.TextField(blank=True, db_column='Ingredients', null=True)),
                ('procedure', models.TextField(blank=True, db_column='Procedure', null=True)),
                ('calories', models.TextField(blank=True, db_column='Calories', null=True)),
                ('total_fat', models.TextField(blank=True, db_column='Total_Fat', null=True)),
                ('saturated_fat', models.TextField(blank=True, db_column='Saturated_Fat', null=True)),
                ('polyunsaturated_fat', models.TextField(blank=True, db_column='Polyunsaturated_Fat', null=True)),
                ('monounsaturated_fat', models.TextField(blank=True, db_column='Monounsaturated_Fat', null=True)),
                ('cholesterol', models.TextField(blank=True, db_column='Cholesterol', null=True)),
                ('sodium', models.TextField(blank=True, db_column='Sodium', null=True)),
                ('potassium', models.TextField(blank=True, db_column='Potassium', null=True)),
                ('total_carbohydrate', models.TextField(blank=True, db_column='Total_Carbohydrate', null=True)),
                ('dietary_fiber', models.TextField(blank=True, db_column='Dietary_Fiber', null=True)),
                ('sugars', models.TextField(blank=True, db_column='Sugars', null=True)),
                ('protein', models.TextField(blank=True, db_column='Protein', null=True)),
                ('vitamin_a', models.TextField(blank=True, db_column='Vitamin_A', null=True)),
                ('vitamin_b12', models.TextField(blank=True, db_column='Vitamin_B12', null=True)),
                ('vitamin_b6', models.TextField(blank=True, db_column='Vitamin_B6', null=True)),
                ('vitamin_c', models.TextField(blank=True, db_column='Vitamin_C', null=True)),
                ('vitamin_d', models.TextField(blank=True, db_column='Vitamin_D', null=True)),
                ('vitamin_e', models.TextField(blank=True, db_column='Vitamin_E', null=True)),
                ('calcium', models.TextField(blank=True, db_column='Calcium', null=True)),
                ('copper', models.TextField(blank=True, db_column='Copper', null=True)),
                ('folate', models.TextField(blank=True, db_column='Folate', null=True)),
                ('iron', models.TextField(blank=True, db_column='Iron', null=True)),
                ('magnesium', models.TextField(blank=True, db_column='Magnesium', null=True)),
                ('manganese', models.TextField(blank=True, db_column='Manganese', null=True)),
                ('niacin', models.TextField(blank=True, db_column='Niacin', null=True)),
                ('pantothenic_acid', models.TextField(blank=True, db_column='Pantothenic_Acid', null=True)),
                ('phosphorus', models.TextField(blank=True, db_column='Phosphorus', null=True)),
                ('riboflavin', models.TextField(blank=True, db_column='Riboflavin', null=True)),
                ('selenium', models.TextField(blank=True, db_column='Selenium', null=True)),
                ('thiamin', models.TextField(blank=True, db_column='Thiamin', null=True)),
                ('zinc', models.TextField(blank=True, db_column='Zinc', null=True)),
            ],
        ),
    ]
